title: Mohamed El Guendouz
description: >
  Ingénieur en informatique et Systèmes d'Information
permalink: ':title/'
baseurl: "" 
url: "https://mohamedelguendouz.github.io"
site-twitter: 

# Author Settings
author: Mohamed El Guendouz
author-img: profil.jfif
about-author: Je suis un ingénieur en informatique temrinant sa dernière année en alternance chez Banque PSA Finance.
social-twitter: 
social-facebook:
social-github: MohamedElGuendouz
social-linkedin: melg-0686aa151
social-email: mohamed.elguendouz@outlook.fr

# Disqus
discus-identifier: mr-brown

# Tracker
analytics: G-42EV5L5LRG

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
